### ISSUE TITLE
This input have one "autofocus" that no have sense.

### ISSUE THREAD

**Issue by frodrisan** [20H-Talent/ikigai-project-3-annasauciuc#6]
https://github.com/20H-Talent/ikigai-project-3-annasauciuc/blob/f2ec0dd845dd7f083b4d2ec4f47df1583acee03a/index.html#L42

**Comment by annasauciuc** [comment]
It is the mock up the focus area on "Street address"

**Comment by frodrisan** [comment]
Ok, leave this issue pending then because I have to ask. Because I saw it as an example of the style you have to have when element's selected, not the way you've interpreted it.

**Comment by annasauciuc** [comment]
Autofocus changed to name input
