### ISSUE TITLE
Why used <nav> and no <header> here?

### ISSUE THREAD

**Issue by frodrisan** [20H-Talent/ikigai-project-3-annasauciuc#7]
https://github.com/20H-Talent/ikigai-project-3-annasauciuc/blob/f2ec0dd845dd7f083b4d2ec4f47df1583acee03a/index.html#L15

**Comment by annasauciuc** [comment]
porque se puede poner un nav fuera del header,y me facilito a mi el styling :)

**Comment by annasauciuc** [comment]
Because you can put a nav out of a  header section and made my css styling easier

**Comment by frodrisan** [comment]
> **Definition and Usage**
> The \<nav\> tag defines a set of navigation links.

By definition the label would be misused, for what you say you could have used a div with a class.
